language: clojure
lein: lein2
jdk:
- openjdk7
install: true
script:
- cd tbot;lein uberjar
- cd quote-builder-800;lein uberjar
deploy:
- provider: releases
  api_key:
    secure: rIif4kcyIftvKyR56BN6DdtSMdEagWuBuY04KDDYYlOZURbKueKJndMpci77qzStIp+vNzV7d5dTGJzkhmLzpnVhnFcYE1vetsJlp9VIfuAYEzcke2AlnCkbHRMIzlspaTGqDCsbTgTbG4SnMF9s2JVhFiVFPQpKqJpuWfB0sls=
  skip_cleanup: true
  file: 
  - /home/travis/build/ohyecloudy/tbot-800/quote-builder-800/target/quote-builder-800-standalone.jar
  - /home/travis/build/ohyecloudy/tbot-800/tbot/target/tbot-standalone.jar
  on:
    tags: true
    all_branches: true
    repo: ohyecloudy/tbot-800
- provider: heroku
  api_key:
    secure: mRRHeTjMSJ0gqg9aVQOghRjAVYX+kW2LKL38rLVZb8rWKbsfncl60s8S2WVr0UbqJx5Tls3p8RJaS0Yo61W/8/H6zBPl15zD2+Jhk//E5IA+mku16ZMUw86tNWODKO0vhk8BwNXrSjmk+Wg/e8hsP2PqliQMrNIZK6vAnd0p0oU=
  app: tbot-800-heroku
  skip_cleanup: true
  file:
  - /home/travis/build/ohyecloudy/tbot-800/tbot/target/tbot-standalone.jar
  on:
    tags: true
    all_branches: true
    repo: ohyecloudy/tbot-800

